### ISSUE TITLE
Occurrence form reports that the reference number is missing for rows above 10 when 10 is the number of rows to be displayed in the data entry settings

### ISSUE THREAD

**Issue by markuhen** [paleobiodb/classic#203] opened 2024-07-19 19:20 UTC

**Comment by mmcclenn** [comment] 2024-07-22 19:09
Mark, I can't figure out how to reproduce this bug. Perhaps we can talk about it on Wednesday?

**Comment by mmcclenn** [comment] 2024-07-27 23:12
This is now fixed. As part of the fix, I removed the data entry setting "Collection no. in occurrence form". Apparently at some point in the past, this setting allowed you to edit the collection number displayed on the occurrence list form. It no longer does this, and its only effect at this point seems to be to cause the bug reported here. So I removed it completely. Can you please check this, and confirm that the occurrence list is now working properly for you?

**Closed** 2024-07-27 23:12 UTC
