### ISSUE TITLE
Reidentified taxa assigned to unranked clades not displaying on collection page

### ISSUE THREAD

**Issue by jpjenk** [paleobiodb/classic#2] opened 2017-01-24 03:23 UTC
Example:

https://paleobiodb.org/classic/basicCollectionSearch?collection_no=120887

This collection has two taxa, but only one displays. Both are visible on the edit screen, but the taxon that has been reidentified and assigned to an unranked clade does not appear except in edit mode.

**Comment by markuhen** [comment] 2017-03-14 15:41
I think this is the same bug as in #33

**Comment by markuhen** [comment] 2017-06-28 20:43
Duplicate of #33

**Comment by jpjenk** [comment] 2017-07-06 23:58
After investigation, this was determined not to be a duplicate of #33

**Closed** 2020-06-22 14:36 UTC
